### ISSUE TITLE
Users are having errors when logging in via discord

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#106]
Returning error post login. Looks like it has something to do with duplicate usernames into the schema. The only user in the database is my user.

```
2022-11-23 20:51:21.596: /var/task/node_modules/mongodb/lib/core/error.js:59
    return new MongoError(options);
           ^

MongoError: E11000 duplicate key error collection: test.users index: userName_1 dup key: { userName: null }
    at Function.create (/var/task/node_modules/mongodb/lib/core/error.js:59:12)
    at toError (/var/task/node_modules/mongodb/lib/utils.js:130:22)
    at /var/task/node_modules/mongodb/lib/operations/common_functions.js:258:39
    at handler (/var/task/node_modules/mongodb/lib/core/sdam/topology.js:961:24)
    at /var/task/node_modules/mongodb/lib/cmap/connection_pool.js:352:13
    at handleOperationResult (/var/task/node_modules/mongodb/lib/core/sdam/server.js:567:5)
    at MessageStream.messageHandler (/var/task/node_modules/mongodb/lib/cmap/connection.js:308:5)
    at MessageStream.emit (node:events:527:28)
    at processIncomingData (/var/task/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/var/task/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  driver: true,
  index: 0,
  code: 11000,
  keyPattern: { userName: 1 },
  keyValue: { userName: null }
}
```
## Task
- Fork the development branch
- Investigate what is causing this error
- Implement fix and pull request to development branch

**Comment by JoeDravarol** [comment]
A potential fix is to update User model `displayName` to non-unique. Although it is very unlikely, it is possible that 2 Discord user can have the same display name and discord tag.

**Comment by Caleb-Cohen** [comment]
```
2022-11-23 22:28:30.480: TokenError: Invalid "code" in request.
    at Strategy.OAuth2Strategy.parseErrorResponse (/var/task/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at Strategy.OAuth2Strategy._createOAuthError (/var/task/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /var/task/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /var/task/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/var/task/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/var/task/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Caleb-Cohen** [comment]
Had to drop the user collection to resolve.
